# Generated by Django 4.1.5 on 2023-01-14 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_ststus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ststus',
            new_name='status',
        ),
    ]
